
version: 2

sources:
  - name: test_table_sources
    database: bigquery-public-data
    schema: austin_bikeshare
    tables: 
      - name: bikeshare_stations
      - name: bikeshare_trips

            